### ISSUE TITLE
iOS 10.1

### ISSUE THREAD

**Issue by AMJ-7** [anewcorp/iPhoneOS-Platform-DeviceSupport-DeveloperImage-dmg#1]
- support iOS 10.1 developer image ... Please

**Comment by iakashpaul** [comment]
http://dropbox.com/s/mg8xp09srnq26l1/10.0%20%2814A345%29.zip?dl=0
#1 10.0, should work with 10.1 too.

**Comment by AMJ-7** [comment]
NO, it's doesn't worked

**Comment by AMJ-7** [comment]
i found solve in the website with this image of iOS 10.1 ... http://www.filedropper.com/10114b65
